---

# Install host

# for now fail if it's not a Red Hat based system
- name: debug ansible distribution
  debug:
    var: hostvars[inventory_hostname]
  tags: debug_info
 
- name: Check OS (common)
  fail: msg="Not a Red Hat based system!"
  when: ansible_os_family != 'RedHat'

- name: Installation for Red Hat
  include: redhat.yml
