---

# Install Greenplum Database v4


# for now fail if it's not a Red Hat based system
- name: Check OS (GPDB v4)
  fail: msg="Not a Red Hat based system!"
  when: ansible_os_family != 'RedHat'


- name: Installation for Red Hat / CentOS
  include: redhat.yml
